Repository ayushjainrksh/conactivity, pull requests merged in 2020-10, with the labels that each got.

#30 change selector for profile links
  scrape.js
Labels: bug

#37 Add networkidle2 while visiting profiles
  scrape.js
Labels: bug

#36 Add feature to log output to a text file for persistance
  .gitignore
  scrape.js
Labels: Hacktoberfest, enhancement

#35 Improve algo
  scrape.js
Labels: enhancement

#44 Major code refactor
  scrape.js
Labels: code quality

#51 Added jsdoc
  scrape.js
Labels: documentation
