Repository ayushjainrksh/conactivity, pull requests merged in 2020-09, with the labels that each got.

#18 Fix PR greeting GitHub action
  .github/workflows/greetings.yml
Labels: bug

#22 Add all contributor
  .all-contributorsrc
  README.md
  package.json
Labels: documentation

#28 Store session in cookies
  .gitignore
  package.json
  scrape.js
Labels: enhancement

#27 Proofread the documentation and fix grammatical errors
  CONTRIBUTING.md
  README.md
Labels: documentation
